### ISSUE TITLE
API Doc Fixes

### ISSUE THREAD

**Issue by jakenathanson** [kraigh/serverless-todo-api#4]
Hi,
I found 3 quick fixes in the API documentation. I was looking to do a pull request for the documentation but the api documentation does not seem to be in the repo. 

The 3 things I found: 

LIST All ToDos: 
`xhttp.open("GET", "https://api.kraigh.net/todos, true); `
should become  `xhttp.open("GET", "https://api.kraigh.net/todos", true); `(Missing Close "")

POST New ToDos and GET a ToDo:
`xhr.setRequestHeader("x-api-key", "abc123");` should become  `xhttp2.setRequestHeader` to match the rest of the code because xhr is called xhttp2 in both these code snippets. 

Thanks!

**Comment by kraigh** [comment]
Hey @jakenathanson good catches. The documentation is in the repo- look in `static/todo-api`.

If you want to do a PR go for it, make sure to set the "base fork" to "kraigh/serverless-todo-api". I'm working on fixing that, the project was originally a fork of another but it makes PRs a little annoying.

**Comment by kraigh** [comment]
Merged and deployed, thanks!
